#version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  kafka-format:
    image: apache/kafka:3.7.0
    environment:
      # ← 여기서 그냥 문자열로 고정
      KAFKA_CLUSTER_ID: "my-fixed-cluster-id-12345"
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - kafka_data:/var/lib/kafka/data
    entrypoint:
      - /bin/bash
      - -lc
      - |
        if [ ! -f /var/lib/kafka/data/meta.properties ]; then
          echo "Formatting storage with Cluster ID: ${KAFKA_CLUSTER_ID}"
          /opt/kafka/bin/kafka-storage.sh format \
            -t "${KAFKA_CLUSTER_ID}" \
            -c /opt/kafka/config/kraft/server.properties
        else
          echo "meta.properties already exists. Skipping format."
        fi
    restart: "no"

  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    ports:
      - "19092:19092"   # 호스트(mac)에서 접속할 포트
    environment:
      # KRaft
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: "1"

    # 리스너 3종: 내부(INTERNAL), 외부(EXTERNAL), 컨트롤러(CONTROLLER)
      KAFKA_LISTENERS: "INTERNAL://:9092,EXTERNAL://:19092,CONTROLLER://:29093"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:9092,EXTERNAL://localhost:19092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"

      # 단일 노드 필수
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"

      # 스토리지/클러스터ID
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      KAFKA_CLUSTER_ID: "my-fixed-cluster-id-12345"
    volumes:
      - kafka_data:/var/lib/kafka/data

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      LOKI_HTTP_URL: "http://host.docker.internal:3100"
      TZ: Asia/Seoul
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    command: >
      mysqld
      --bind-address=0.0.0.0
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --skip-name-resolve=ON
    environment:
      MYSQL_ROOT_PASSWORD: pass1234
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    volumes:
      - ./mysql-data:/var/lib/mysql

  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    ports:
      - "15672:15672" # Management interface
      - "5672:5672"   # RabbitMQ client

  fluentbit:
    image: fluent/fluent-bit:2.1
    container_name: fluentbit
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
#    depends_on:
#      - elasticsearch
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    environment:
      OTEL_HOST: "host.docker.internal"
      OTEL_HTTP_PORT: "4318"

#https://grafana.com/docs/opentelemetry/docker-lgtm/
  otel-collector:
#    image: otel/opentelemetry-collector-contrib:latest
    image: otel/opentelemetry-collector-contrib:0.138.0
#    image: grafana/otel-lgtm:0.11.17
    container_name: otel-collector
    volumes:
      - ./otel-collector-config-local.yaml:/etc/otelcol/config.yaml
    command: [ "--config=/etc/otelcol/config.yaml" ]
#    command: ["/otelcol", "--config=/etc/otelcol/config.yaml"]
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
#    depends_on:
#      - zipkin
    environment:
      LOKI_ENDPOINT: "http://host.docker.internal:3100/loki/api/v1/push"
      ZIPKIN_ENDPOINT: "http://host.docker.internal:9411/api/v2/spans"
      ES_ENDPOINT: "http://host.docker.internal:9200"
      TZ: Asia/Seoul
    restart: always


  loki:
    image: grafana/loki:3.5
    container_name: loki
    ports:
      - "3100:3100"
    command: ["-config.file=/etc/loki/config.yaml"]
    volumes:
      - ./loki-config.yaml:/etc/loki/config.yaml:ro
      - ./loki-data:/var/loki
    restart: always
    environment:
      - TZ=Asia/Seoul

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    environment:
      - TZ=Asia/Seoul

  vault:
    image: hashicorp/vault:1.16
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    cap_add:
      - IPC_LOCK


volumes:
  kafka_data: {}