receivers:
  otlp:
    protocols:
      http:
      grpc:

processors:
  batch: {}
  resource:
    attributes:
      - key: service.namespace
        value: origemite
        action: upsert

exporters:
  zipkin:
#    endpoint: "http://zipkin:9411/api/v2/spans"
    endpoint: "http://host.docker.internal:9411/api/v2/spans"
  elasticsearch:
    endpoints: ["http://host.docker.internal:9200"]
    logs_index: "otel-logs"
  otlphttp: # Loki로 OTLP로 보낼 때
    endpoint: "http://host.docker.internal:3100/otlp"
    tls:
      insecure: true

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [otlphttp, elasticsearch]
    traces:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [zipkin, otlphttp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]
