#receivers:
#  otlp:
#    protocols:
#      http:
#        endpoint: "0.0.0.0:4318"
#      grpc:
#        endpoint: "0.0.0.0:4317"
#
#processors:
#  batch: {}
#
#exporters:
#  loki:
#    endpoint: "http://host.docker.internal:3100/loki/api/v1/push"
#  zipkin:
##    endpoint: "http://zipkin:9411/api/v2/spans"
#    endpoint: "http://host.docker.internal:9411/api/v2/spans"
#
#service:
#  pipelines:
#    logs:
#      receivers: [otlp]
#      processors: [resource, batch]
#      exporters: [loki]
#    traces:
#      receivers: [otlp]
#      processors: [resource, batch]
#      exporters: [zipkin]
#    metrics:
#      receivers: [otlp]
#      processors: [batch]
#      exporters: []


receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"
      grpc:
        endpoint: "0.0.0.0:4317"

processors:
  batch: {}

exporters:
  otlphttp:
#    endpoint: "http://host.docker.internal:3100/otlp"
#    endpoint: "http://host.docker.internal:3100/loki/api/v1/push"
#  loki:
#    endpoint: http://host.docker.internal:3100/loki/api/v1/push
    logs_endpoint: http://host.docker.internal:3100/otlp/v1/logs
#    endpoints:
#      traces: http://host.docker.internal:3100/otlp/v1/traces
#      logs:   http://host.docker.internal:3100/otlp/v1/logs

  zipkin:
#    endpoint: "http://zipkin:9411/api/v2/spans"
    endpoint: "http://host.docker.internal:9411/api/v2/spans"

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [zipkin]
#    metrics:
#      receivers: [otlp]
#      processors: [batch]
#      exporters: []
